---
title: "vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ProjectSTSCI4520)
```

```{r}
# map of the average temperature of stations in March 2024 vs the interpolated data map
march_2024_data <- daily_weather |> dplyr:::filter(LST_DATE >= "2024-03-01", LST_DATE < "2024-04-01") |> dplyr:::group_by(`station name`, LONGITUDE, LATITUDE) |> dplyr:::summarise(avg_temp = mean(T_DAILY_AVG))

maps::map("usa")
points(march_2024_data$LONGITUDE, march_2024_data$LATITUDE, pch = 16, col =  hcl.colors(10)[cut(march_2024_data$avg_temp, 10)])
legend("topright", title="Temperature",legend= levels(cut(march_2024_data$avg_temp, 10)), col = hcl.colors(10), pch=20)
title("Average Temperature (°C) in March 2024")

rand = rnorm(nrow(march_2024_data), 0, 10)

grid <- create_grid(resolution_X = 100, resolution_Y=100)
interp_data = interpolate_data(march_2024_data$avg_temp, march_2024_data$LONGITUDE, march_2024_data$LATITUDE, gridpoints = grid)
plot_interpolations(interp_data)
title("Average Interpolated Temperature (°C) in March 2024")
```



```{r}
num_stations = nrow(station_info)
stations_high_day = rep(NA, times = num_stations)
stations_low_day = rep(NA, times = num_stations)

i = 1
for (station_id in station_info$WBANNO){
  yearly_estimates = get_yearly_cycle(station_id)
  min_row = which.min(yearly_estimates$avgTemp)
  max_row = which.max(yearly_estimates$avgTemp)
  stations_high_day[i] = yearly_estimates[max_row, "dayofY"]
  stations_low_day[i] = yearly_estimates[min_row, "dayofY"]
  i = i + 1
}
maps::map("usa")
points(station_info$LONGITUDE, station_info$LATITUDE, pch = 16, col =  hcl.colors(10)[cut(stations_high_day, 10)])
legend("topright", title="Day of the Year",legend= levels(cut(stations_high_day, 10)), col = hcl.colors(10), pch=20)
title("Warmest Day of the Year")

maps::map("usa")
points(station_info$LONGITUDE, station_info$LATITUDE, pch = 16, col =  hcl.colors(10)[cut(stations_low_day, 10)])
legend("topright", title="Day of the Year",legend= levels(cut(stations_low_day, 10)), col = hcl.colors(10), pch=20)
title("Warmest Day of the Year")

high_day_interp_data = interpolate_data(stations_high_day, station_info$LONGITUDE, station_info$LATITUDE, gridpoints = grid)
plot_interpolations(high_day_interp_data)
title("Interpolated Warmest Day of the Year")

low_day_interp_data = interpolate_data(stations_low_day, station_info$LONGITUDE, station_info$LATITUDE, gridpoints = grid)
plot_interpolations(low_day_interp_data)
title("Interpolated Coldest Day of the Year")
```

```{r}
diverse_stations_ids = c(63828, 94060, 4994, 64758, 53152, 94092, 53968, 94645, 54808, 4223)
diverse_stations = station_info[station_info$WBANNO %in% diverse_stations_ids,]
diverse_stations

yearly_cycles = rep(NA, times = 10)

plot(1, xlab="", ylab="", xlim=c(1, 365), ylim=c(-20, 30))
i = 1
for (station_id in diverse_stations_ids){
  yearly_cycle = get_yearly_cycle(station_id)
  points(x = yearly_cycle$dayofY, y = yearly_cycle$avgTemp, type = "l", col = i)
  i = i + 1
}
legend(x="right", inset=c(-0.2,0), title="Station", legend = diverse_stations, col = 1:10, pch=20)

```



